name: cscalprod
channels:
  - conda-forge
dependencies:
  - python=3.12
  - xarray=2024.6.0
  - dask=2024.7.0
  - dask-core=2024.7.0
  - dask-expr=1.1.7
  - bottleneck=1.4.0
  - numpy=2.0.0
  - pandas=2.2.2
  - scipy=1.14.0
  - cartopy=0.23.0
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.6
  - pyhdf=0.11.4
  - netcdf4=1.7.1
