channels:
  - conda-forge
dependencies:
  - python=3.8.11
  - matplotlib=3.4.3
  - numpy=1.21.2
  - pandas=1.3.3
  - xarray=0.19.0
  - cartopy=0.19.0.post1
  - dask=2021.12.0
  - pyhdf=0.10.3
  - bottleneck=1.3.4
  - netcdf4=1.5.7
  - scipy=1.7.1